### PR TITLE
now no need to magic value for n_stops

### PR DESCRIPTION
**Pull request by kdyjedes**
This is small fix, but it helps us to use the testerrrr with the -r param which we occasionally use.

### CODE REVIEW

**Comment by skinkie** [comment]
Thanks! But you you please split a whitespace fix pull request and the actual fix?

**Comment by kdyjedes** [comment]
And sorry, it seems there is a lot of changes, because my vim is set to remove spaces at the end of line.

There are changes only where the **router_request_randomize** is.

**Comment by kdyjedes** [comment]
Ok, sorry, I'll fix it one more time. I realized it now in github's diff.

**Comment by skinkie** [comment]
I am interested in your .vimrc how vim is doing this ;)

**Comment by kdyjedes** [comment]
This is what I have in ~/.gvimc

https://gist.github.com/kdyjedes/7303326

**Comment by skinkie** [comment]
Thanks. Keep up the good work!

**Comment by kdyjedes** [comment]
Thank You for merge.

We have some other fixes. We'll push it soon. Now we have some new troubles with building graph after last pull. Can I tell You details?

**Comment by skinkie** [comment]
Do make an issue here on github :-) So we can comment on it.

**Comment by koch-t** [comment]
We've did some major refactoring of the graph, if you can give a synopsis
of the error, i'm sure we can fix it.

**Comment by kdyjedes** [comment]
I'll make an issue. Thanks.

**Comment by kdyjedes** [comment]
Oh, so, my bad. Everything works fine.

Explanation: we added an exception to timetable.py because of an error in our data. It looks like (from line 571)

``` python
for route in zip (*route_t_fields) :
    # print route
    try :
      out.write(route_t.pack(*route));
    except :
      print "EXCEPT for ", route
      continue
```

And I make a mistake in copying this code to new timetable.py.

BTW, we made the bash script to easier graph building. Consider adding it to the repo.
https://gist.github.com/kdyjedes/b902ef858d08bbc007e4

**Comment by koch-t** [comment]
Is it an true error in the data or is it just a mistaken assumption we made
regarding GTFS datafeeds?
Also asking whether we should put in more datavalidation during GTFS
reading.

**Comment by kdyjedes** [comment]
Well, the error, that is raised is:
struct.error: ushort format requires 0 <= number <= USHRT_MAX

It appears for only one record:
(11153, 1329, 0, 34, 1, 4, 4, 1219, 0, 13830, 70860)

It seems to be datatype error.

**Comment by koch-t** [comment]
Ah i see what's going on there.

(11153, 1329, 0, 34, 1, 4, 4, 1219, 0, 13830, 70860)

The last value (70860) is the maximum time a trip end on that specific
route. Don't know which kind of data you're using but check for some
extreme late times in stop_times. It could be correct for some very long
nighttrains, but 70860 is a trip ending at 283440 seconds after midnight.
PS.
Best not to workaround just like you did. It will make things go out of
sync, better to write an empty struct.

**Comment by kdyjedes** [comment]
Thank You for that hint. Very helpful.

Yes, I know it isn't good solution. It is fix from the first day we met rrrr :)

**Pull request merged**
