### PR TITLE
Implemented cancelable rounded router.

### PR DESCRIPTION
**Pull request by elslooo**
- I created a new function router_route_in_rounds that _won't_ execute the _round calls (yes, it's a feature). Instead, the callee is responsible for that. This enables (app) developers to cancel a route request (just don't call _round anymore when the request is cancelled).

### CODE REVIEW

**Comment by skinkie** [comment]
What is the reason that you have implemented this opposed to use max_transfers?

**Comment by koch-t** [comment]
Yes unless the idea is to "cancel" the search by modifying router->n_rounds from another thread?

**Comment by elslooo** [comment]
The idea is to have one thread:
- keep running until a thread-local variable "cancelled" is set to true
- this thread runs something like this:

```
    for (i = 0; i < route->n_rounds; i++)
        if (self.isCancelled)
            break;
        router_route(...);
    }
```

Then another thread (e.g. the UI thread):
- Sets the first thread's "cancelled" variable to true.

Now with the appropriate locking (Objective-C provides this), this is able to cancel a route request. In my Teova app, this is used to cancel generating the shortest route in the auto-suggestion box. When a user types A for example, it starts generating the shortest routes for both Almere and Amsterdam. Then when the user types an m, it cancels the Almere route and continues calculating the Amsterdam route. Given that a user usually types quicker than the router is able to generate a journey, this ensures that the app runs smoothly.

**Comment by skinkie** [comment]
You do understand that the only thing you require for that feature is the origin location? Every arrival time is known, no need to redo any query. Requires one if statement in the planner to enable this feature ;) Or actually: to disable the optimisation.

**Comment by elslooo** [comment]
It's usually the same arrival location but a different origin (or the same origin and a different arrival location).

**Comment by koch-t** [comment]
Doesn't really matter as long as either origin or destination is known

**Comment by skinkie** [comment]
So if you either know the departure time + origin, or arrival time + destination we can directly give you all the pairs, virtually for free. So your autocomplete could already show the time it takes to get you there or when you need to leave.

**Comment by koch-t** [comment]
To be specific that's issue #13

**Pull request closed without merging**
