### PR TITLE
Use prefix for library type "route"

### PR DESCRIPTION
**Pull request by oooits72**
route_t defined in "/usr/include/sys/kernel_types.h" on OS X as "typedef struct __rtentry\* route_t;".
It's not possible to redefine it with different type (route).

Problem occurs when I trying to build rrrr for iOS.

The solution is to use prefix for library type "route".

### CODE REVIEW

**Comment by skinkie** [comment]
I'll consider this requirement for the ansi branch.

**Comment by JordenVerwer** [comment]
Wouldn't it be better to prevent unwanted system headers from being included? A name like route_t is a perfectly valid identifier that's not reserved for the implementation or future standardization.

**Comment by skinkie** [comment]
Do you have an idea how this include ended up there?

**Comment by JordenVerwer** [comment]
It's probably being included indirectly through some other header, which is possibly also affected by compiler options (gnu89/gnu99/gnu11 are more likely to include unwanted junk than c89/c99/c11). I don't have an iOS build environment available, so I can't try for myself.

**Pull request closed without merging**
